#!/bin/bash
#SBATCH --account=agmisc
#SBATCH --job-name=hb_thread_test
#SBATCH --partition=fuchs
#SBATCH --qos=fuchs
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=0
#SBATCH --time=12:00:00
#SBATCH --output=logs/hb_thread_test_%j.out
#SBATCH --error=logs/hb_thread_test_%j.err

set -euo pipefail

PROJECT_DIR="/work/mesonqcd/barros/SU23_freezing/Topological-freezing-in-SU2-3-simulations"
cd "$PROJECT_DIR"

mkdir -p logs data/thread_test

# Default is a quick smoke test; increase NUM_SWEEPS for stable timing comparisons.
THREADS_LIST=(1 2 4 8)
NUM_SWEEPS=10
SAVE_INTERVAL=1

SETUP_FILES=(
    "input/setup_41x41_periodic_su2.txt"
    "input/setup_57x41_open_su2.txt"
)

HEATBATH_BIN="build/bin/mc_heatbath"
if [ ! -x "$HEATBATH_BIN" ]; then
    echo "[INFO] Heatbath binary not found, building release..."
    ./scripts/build.sh release
fi

CSV="data/thread_test/hb_thread_test_${SLURM_JOB_ID:-local}.csv"
echo "setup_file,T,L,boundary,beta,threads,num_sweeps,elapsed_seconds,run_dir" > "$CSV"

read_param() {
    grep -E "^${1}[[:space:]]+" "$2" | awk '{print $2}' | head -1
}

for setup_file in "${SETUP_FILES[@]}"; do
    if [ ! -f "$setup_file" ]; then
        echo "[WARN] Missing setup file: $setup_file (skipping)"
        continue
    fi

    T=$(read_param "T" "$setup_file")
    L=$(read_param "L" "$setup_file")
    BOUNDARY=$(read_param "boundary" "$setup_file")
    BETA=$(grep -E '^beta[[:space:]]+' "$setup_file" | awk '{print $2}' | head -1)

    BOUNDARY=${BOUNDARY:-periodic}
    if [ -z "${BETA:-}" ]; then
        echo "[WARN] No beta value found in $setup_file (skipping)"
        continue
    fi

    echo "============================================================"
    echo "[INFO] Benchmarking ${setup_file}: T=${T}, L=${L}, boundary=${BOUNDARY}, beta=${BETA}"
    echo "============================================================"

    for threads in "${THREADS_LIST[@]}"; do
        export OMP_NUM_THREADS="$threads"
        export OMP_PROC_BIND=spread
        export OMP_PLACES=cores

        seed=$(( (RANDOM + 1) * 100000 + threads * 997 ))
        run_dir="data/thread_test/T${T}_L${L}_b${BETA}_${BOUNDARY}_omp${threads}_seed${seed}"
        out_dir="$run_dir/output"
        cfg_dir="$run_dir/configs"
        input_file="$run_dir/input.txt"

        mkdir -p "$out_dir" "$cfg_dir"

        cat > "$input_file" << EOF
# Auto-generated by cluster/fuchs_heatbath_thread_test.sh
T                   ${T}
L                   ${L}
beta                ${BETA}
seed                ${seed}
start_type          cold
boundary            ${BOUNDARY}
num_sweeps          ${NUM_SWEEPS}
save_interval       ${SAVE_INTERVAL}

output_dir          ${out_dir}/
config_dir          ${cfg_dir}/
EOF

        echo "[RUN] setup=$(basename "$setup_file") threads=$threads sweeps=$NUM_SWEEPS"
        t0=$(date +%s)
        "$HEATBATH_BIN" -i "$input_file" > "$run_dir/heatbath.log" 2>&1
        t1=$(date +%s)
        dt=$((t1 - t0))

        echo "[OK] threads=$threads elapsed=${dt}s"
        echo "$(basename "$setup_file"),${T},${L},${BOUNDARY},${BETA},${threads},${NUM_SWEEPS},${dt},${run_dir}" >> "$CSV"
    done
done

echo ""
echo "[DONE] Thread benchmark finished"
echo "[DONE] Summary CSV: $CSV"
