#!/bin/bash
#SBATCH --account=mesonqcd
#SBATCH --job-name=su3_topcharge
#SBATCH --partition=general2
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=40
#SBATCH --mem=0
#SBATCH --time=14-00:00:00
#SBATCH --output=/work/mesonqcd/barros/SU23_freezing/Topological-freezing-in-SU2-3-simulations/logs/su3_topcharge_%j.out
#SBATCH --error=/work/mesonqcd/barros/SU23_freezing/Topological-freezing-in-SU2-3-simulations/logs/su3_topcharge_%j.err

set -euo pipefail

# Measure SU(3) topological charge on CL2QCD ensembles generated by
# hhlr_su3_cl2qcd_heatbath.sh. Override parameters with:
#   sbatch --export=ALL,NAME=value cluster/hhlr_su3_topcharge.sh

module purge

PROJECT_DIR=/work/mesonqcd/barros/SU23_freezing/Topological-freezing-in-SU2-3-simulations
BUILD_DIR=${BUILD_DIR:-$PROJECT_DIR/build}
TOPCHARGE_BIN=${TOPCHARGE_BIN:-$BUILD_DIR/bin/meas_topcharge_su3}
RESULTS_ROOT=${RESULTS_ROOT:-$PROJECT_DIR/data/results_su3_ensembles}
LOG_DIR=$PROJECT_DIR/logs

RUN_LABEL=${RUN_LABEL:-}
RUN_DIR=${RUN_DIR:-}
RUN_GLOB=${RUN_GLOB:-T*_su3_cl2qcd}

CONFIG_FORMAT=${CONFIG_FORMAT:-cl2qcd_lime}
CONFIG_PREFIX=${CONFIG_PREFIX:-conf.}
CONFIG_POSTFIX=${CONFIG_POSTFIX:-}
CONF_DIGITS=${CONF_DIGITS:-5}

START_CONF=${START_CONF:-}
END_CONF=${END_CONF:-}
CONF_STEP=${CONF_STEP:-}

SMEAR_STEPS=${SMEAR_STEPS:-20}
SMEAR_ALPHA=${SMEAR_ALPHA:-0.3}
EXCLUDE_BOUNDARY_SLICES=${EXCLUDE_BOUNDARY_SLICES:-}

BUILD_TOPCHARGE=${BUILD_TOPCHARGE:-true}
BUILD_JOBS=${BUILD_JOBS:-${SLURM_CPUS_PER_TASK:-40}}

mkdir -p "$LOG_DIR"

if [ "$BUILD_TOPCHARGE" = "true" ] || [ "$BUILD_TOPCHARGE" = "1" ]; then
    echo "Building meas_topcharge_su3..."
    cmake -S "$PROJECT_DIR" -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
    cmake --build "$BUILD_DIR" --target meas_topcharge_su3 -j "$BUILD_JOBS"
fi

if [ ! -x "$TOPCHARGE_BIN" ]; then
    echo "SU(3) topcharge binary is missing or not executable: $TOPCHARGE_BIN" >&2
    exit 1
fi

export OMP_NUM_THREADS=${OMP_NUM_THREADS:-${SLURM_CPUS_PER_TASK:-40}}
export OMP_PROC_BIND=${OMP_PROC_BIND:-spread}
export OMP_PLACES=${OMP_PLACES:-cores}

read_run_info() {
    local key="$1"
    local run_dir="$2"
    local info_file="$run_dir/run_info.txt"
    [ -f "$info_file" ] || return 0
    awk -F= -v key="$key" '$1 == key {print $2; exit}' "$info_file"
}

infer_config_numbers() {
    local config_dir="$1"
    local nums=()
    local path base num

    for path in "$config_dir"/"$CONFIG_PREFIX"*"$CONFIG_POSTFIX"; do
        [ -f "$path" ] || continue
        base=${path##*/}
        num=${base#"$CONFIG_PREFIX"}
        if [ -n "$CONFIG_POSTFIX" ]; then
            num=${num%"$CONFIG_POSTFIX"}
        fi
        if [[ "$num" =~ ^[0-9]+$ ]]; then
            nums+=("$num")
        fi
    done

    if [ "${#nums[@]}" -eq 0 ]; then
        return 1
    fi

    printf '%s\n' "${nums[@]}" | sort -n
}

discover_run_dirs() {
    if [ -n "$RUN_DIR" ]; then
        printf '%s\n' "$RUN_DIR"
        return
    fi

    if [ -n "$RUN_LABEL" ]; then
        printf '%s\n' "$RESULTS_ROOT/$RUN_LABEL"
        return
    fi

    find "$RESULTS_ROOT" -maxdepth 1 -mindepth 1 -type d -name "$RUN_GLOB" | sort
}

normalize_boundary() {
    local boundary="$1"
    case "$boundary" in
        obc|open) echo "open" ;;
        *)        echo "periodic" ;;
    esac
}

read_heatbath_input_flag() {
    local run_dir="$1"
    local input_file
    input_file=$(read_run_info input_file "$run_dir")
    input_file=${input_file:-$run_dir/input_su3heatbath.txt}

    [ -f "$input_file" ] || return 0
    awk -F= '$1 == "useOpenTemporalGaugeBoundary" {gsub(/[[:space:]]/, "", $2); print tolower($2); exit}' "$input_file"
}

infer_boundary() {
    local run_dir="$1"
    local boundary run_name input_flag

    boundary=$(read_run_info boundary "$run_dir")
    if [ -n "$boundary" ]; then
        normalize_boundary "$boundary"
        return
    fi

    run_name=${run_dir##*/}
    case "$run_name" in
        *_open_*|*_obc_*) echo "open"; return ;;
        *_periodic_*)     echo "periodic"; return ;;
    esac

    input_flag=$(read_heatbath_input_flag "$run_dir")
    case "$input_flag" in
        true|1) echo "open" ;;
        *)      echo "periodic" ;;
    esac
}

validate_open_boundary_run() {
    local run_dir="$1"
    local boundary="$2"
    local exclude_bc="$3"
    local ntime="$4"
    local input_flag log_file

    [ "$boundary" = "open" ] || return 0

    if ! [[ "$exclude_bc" =~ ^[0-9]+$ ]]; then
        echo "Open SU(3) topcharge exclusion must be an integer: $exclude_bc" >&2
        return 1
    fi
    if [ "$exclude_bc" -lt 1 ]; then
        echo "Open SU(3) topcharge requires EXCLUDE_BOUNDARY_SLICES >= 1" >&2
        return 1
    fi
    if [ $((2 * exclude_bc)) -ge "$ntime" ]; then
        echo "Open SU(3) topcharge exclusion removes the full temporal extent: T=$ntime, exclude=$exclude_bc" >&2
        return 1
    fi
    if [ "$exclude_bc" -lt 2 ]; then
        echo "Warning: EXCLUDE_BOUNDARY_SLICES=$exclude_bc is a very thin OBC buffer" >&2
    fi

    input_flag=$(read_heatbath_input_flag "$run_dir")
    if [ -z "$input_flag" ]; then
        echo "Warning: could not verify useOpenTemporalGaugeBoundary in heatbath input for $run_dir" >&2
    elif [ "$input_flag" != "true" ] && [ "$input_flag" != "1" ]; then
        echo "Run is marked open, but heatbath input has useOpenTemporalGaugeBoundary=$input_flag" >&2
        return 1
    fi

    log_file="$run_dir/heatbath.log"
    if [ -f "$log_file" ] && ! grep -q "temporal gauge boundary = open" "$log_file"; then
        echo "Run is marked open, but heatbath.log does not confirm 'temporal gauge boundary = open'" >&2
        return 1
    fi
}

measure_run() {
    local run_dir="$1"
    local config_dir="$run_dir/configs"
    local output_dir="$run_dir/output"
    local input_file="$run_dir/input_su3_topcharge.txt"
    local log_file="$run_dir/topcharge_su3.log"

    if [ ! -d "$run_dir" ]; then
        echo "Run directory does not exist: $run_dir" >&2
        return 1
    fi
    if [ ! -d "$config_dir" ]; then
        echo "Config directory does not exist: $config_dir" >&2
        return 1
    fi

    mapfile -t conf_numbers < <(infer_config_numbers "$config_dir")
    if [ "${#conf_numbers[@]}" -eq 0 ]; then
        echo "No matching configs found in $config_dir" >&2
        return 1
    fi

    local nspace ntime boundary exclude_bc start_conf end_conf conf_step checkpoint_every
    nspace=$(read_run_info nSpace "$run_dir")
    ntime=$(read_run_info nTime "$run_dir")
    boundary=$(infer_boundary "$run_dir")

    nspace=${nspace:-${NSPACE:-16}}
    ntime=${ntime:-${NTIME:-16}}

    start_conf=${START_CONF:-${conf_numbers[0]}}
    end_conf=${END_CONF:-${conf_numbers[$((${#conf_numbers[@]} - 1))]}}

    checkpoint_every=$(read_run_info createCheckpointEvery "$run_dir")
    if [ -n "$CONF_STEP" ]; then
        conf_step=$CONF_STEP
    elif [ -n "$checkpoint_every" ] && [ "$checkpoint_every" -gt 0 ]; then
        conf_step=$checkpoint_every
    elif [ "${#conf_numbers[@]}" -gt 1 ]; then
        conf_step=$((10#${conf_numbers[1]} - 10#${conf_numbers[0]}))
    else
        conf_step=1
    fi

    if [ -n "$EXCLUDE_BOUNDARY_SLICES" ]; then
        exclude_bc=$EXCLUDE_BOUNDARY_SLICES
    elif [ "$boundary" = "open" ]; then
        exclude_bc=2
    else
        exclude_bc=0
    fi

    validate_open_boundary_run "$run_dir" "$boundary" "$exclude_bc" "$ntime"

    mkdir -p "$output_dir"

    cat > "$input_file" <<EOF_INPUT
# Auto-generated SU(3) topcharge input
# Generated: $(date)

config_dir        $config_dir
config_format     $CONFIG_FORMAT
config_prefix     $CONFIG_PREFIX
config_postfix    $CONFIG_POSTFIX
conf_digits       $CONF_DIGITS
output_file       $output_dir/topcharge_su3.dat

T                 $ntime
L                 $nspace
start_conf        $start_conf
end_conf          $end_conf
conf_step         $conf_step

smear_steps       $SMEAR_STEPS
smear_alpha       $SMEAR_ALPHA
boundary          $boundary
exclude_boundary_slices $exclude_bc
EOF_INPUT

    echo "Starting SU(3) topcharge"
    echo "Run directory: $run_dir"
    echo "Input file: $input_file"
    echo "Output file: $output_dir/topcharge_su3.dat"
    echo "Binary: $TOPCHARGE_BIN"
    echo "Boundary: $boundary"
    echo "Exclude boundary slices: $exclude_bc"
    echo "OMP_NUM_THREADS: $OMP_NUM_THREADS"

    "$TOPCHARGE_BIN" -i "$input_file" 2>&1 | tee "$log_file"

    cat >> "$run_dir/run_info.txt" <<EOF_INFO

# Topcharge phase
topcharge_generated=$(date)
topcharge_bin=$TOPCHARGE_BIN
topcharge_input_file=$input_file
topcharge_file=$output_dir/topcharge_su3.dat
topcharge_timeslice_file=$output_dir/topcharge_timeslice.dat
topcharge_log=$log_file
topcharge_start_conf=$start_conf
topcharge_end_conf=$end_conf
topcharge_conf_step=$conf_step
topcharge_smear_steps=$SMEAR_STEPS
topcharge_smear_alpha=$SMEAR_ALPHA
topcharge_boundary=$boundary
topcharge_exclude_boundary_slices=$exclude_bc
EOF_INFO
}

mapfile -t run_dirs < <(discover_run_dirs)

if [ "${#run_dirs[@]}" -eq 0 ]; then
    echo "No SU(3) CL2QCD run directories found in $RESULTS_ROOT matching $RUN_GLOB" >&2
    exit 1
fi

echo "SU(3) topcharge run count: ${#run_dirs[@]}"
for run_dir in "${run_dirs[@]}"; do
    echo "------------------------------------------------------------"
    measure_run "$run_dir"
done

echo "All SU(3) topcharge measurements completed."
