#!/bin/bash
#SBATCH --account=mesonqcd
#SBATCH --job-name=qtarget_tc
#SBATCH --partition=general2
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=40
#SBATCH --mem=0
#SBATCH --time=02-00:00:00
#SBATCH --output=/work/mesonqcd/barros/SU23_freezing/Topological-freezing-in-SU2-3-simulations/logs/qtarget_topcharge_%j.out
#SBATCH --error=/work/mesonqcd/barros/SU23_freezing/Topological-freezing-in-SU2-3-simulations/logs/qtarget_topcharge_%j.err

set -euo pipefail

module purge

PROJECT_DIR=/work/mesonqcd/barros/SU23_freezing/Topological-freezing-in-SU2-3-simulations
RUN_DIR=$PROJECT_DIR/data/results/qtarget_T80_L80_b3.15_periodic_20260527_145728_su2/hot_list_-2to-1to0to1to2
CONFIG_DIR=$RUN_DIR/configs
OUTPUT_DIR=$RUN_DIR/output
INPUT_FILE=$RUN_DIR/input_topcharge.txt
TOPCHARGE_PARAMS=$PROJECT_DIR/input/heatbath_input/topcharge_params_su2_finished.txt
TOPCHARGE_BIN=$PROJECT_DIR/build/bin/meas_topcharge

cd "$PROJECT_DIR"
mkdir -p logs

export OMP_NUM_THREADS="${SLURM_CPUS_PER_TASK:-40}"
export OMP_PROC_BIND=spread
export OMP_PLACES=cores

read_param() {
    awk -v key="$1" '$1 == key { print $2; exit }' "$2"
}

if [ ! -d "$CONFIG_DIR" ]; then
    echo "Config directory missing: $CONFIG_DIR" >&2
    exit 1
fi

if [ ! -f "$RUN_DIR/input.txt" ]; then
    echo "Run input file missing: $RUN_DIR/input.txt" >&2
    exit 1
fi

if [ ! -f "$TOPCHARGE_PARAMS" ]; then
    echo "Topcharge parameter file missing: $TOPCHARGE_PARAMS" >&2
    exit 1
fi

if [ ! -x "$TOPCHARGE_BIN" ]; then
    mkdir -p build
    cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    cmake --build build --target meas_topcharge --parallel "${SLURM_CPUS_PER_TASK:-40}"
fi

START_CONF=$(find "$CONFIG_DIR" -maxdepth 1 -type f -name 'conf.*' | sed 's|.*/conf\.||' | sort -n | head -1)
END_CONF=$(find "$CONFIG_DIR" -maxdepth 1 -type f -name 'conf.*' | sed 's|.*/conf\.||' | sort -n | tail -1)
CONF_STEP=$(read_param "save_interval" "$RUN_DIR/input.txt")
SMEAR_STEPS=$(read_param "smear_steps" "$TOPCHARGE_PARAMS")
SMEAR_INTERVAL=$(read_param "smear_interval" "$TOPCHARGE_PARAMS")
SMEAR_ALPHA=$(read_param "smear_alpha" "$TOPCHARGE_PARAMS")

if [ -z "$START_CONF" ] || [ -z "$END_CONF" ]; then
    echo "No conf.* files found in $CONFIG_DIR" >&2
    exit 1
fi

START_CONF=$((10#$START_CONF))
END_CONF=$((10#$END_CONF))
CONF_STEP=${CONF_STEP:-100}
SMEAR_STEPS=${SMEAR_STEPS:-15}
SMEAR_INTERVAL=${SMEAR_INTERVAL:-$SMEAR_STEPS}
SMEAR_ALPHA=${SMEAR_ALPHA:-0.3}

mkdir -p "$OUTPUT_DIR"

cat > "$INPUT_FILE" << EOF
# Auto-generated by cluster/hhlr_topcharge.sh
T                       $(read_param "T" "$RUN_DIR/input.txt")
L                       $(read_param "L" "$RUN_DIR/input.txt")
beta                    $(read_param "beta" "$RUN_DIR/input.txt")
seed                    $(read_param "seed" "$RUN_DIR/input.txt")
boundary                $(read_param "boundary" "$RUN_DIR/input.txt")

config_dir              ${CONFIG_DIR}/
output_dir              ${OUTPUT_DIR}/

start_conf              $START_CONF
end_conf                $END_CONF
conf_step               $CONF_STEP
smear_steps             $SMEAR_STEPS
smear_interval          $SMEAR_INTERVAL
smear_alpha             $SMEAR_ALPHA
exclude_boundary_slices 0
EOF

echo "Measuring SU(2) topological charge"
echo "  run dir:      $RUN_DIR"
echo "  configs:      conf.$(printf '%04d' "$START_CONF") through conf.$(printf '%04d' "$END_CONF") step $CONF_STEP"
echo "  input file:   $INPUT_FILE"
echo "  output file:  $OUTPUT_DIR/topcharge.dat"
echo "  threads:      $OMP_NUM_THREADS"
echo ""

"$TOPCHARGE_BIN" -i "$INPUT_FILE" 2>&1 | tee "$RUN_DIR/topcharge.log"
